[package]
name = "luisa_compute_api_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"

[build-dependencies]
cbindgen = "0.24.3"


[lib]
crate-type = ["staticlib", "rlib"]
name = "luisa_compute_api_types"
