[package]
name = "luisa_compute_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
luisa_compute_ir = { path = "../luisa_compute_ir" }
luisa_compute_api_types = { path = "../luisa_compute_api_types" }
luisa_compute_cpu_kernel_defs = { path = "../luisa_compute_cpu_kernel_defs" }
libc = "0.2"
rayon = "1.6.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
sha2 = "0.10"
libloading = "0.7"
log = "0.4"
parking_lot = "0.12.1"
embree_sys = {git = "https://github.com/shiinamiyuki/embree-sys"}
lazy_static = "1.4.0"