name: CI

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Install Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential cmake ninja-build git file libopenimageio-dev libopencv-dev
      - name: "Configure and Build"
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc -D CMAKE_CXX_COMPILER=g++
          cmake --build build

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Install Dependencies"
        run: |
          brew install cmake ninja openimageio opencv pybind11 llvm
      - name: "Configure and Build"
        run: |
          export PATH=$PATH:/usr/local/opt/llvm/bin
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -D CMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++
          cmake --build build

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Configure and Build"
        run: |
          cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
          cmake --build build
