name: CI

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Pull Submodules"
        run: |
          git submodule update --init --recursive
      - name: "Install Dependencies"
        run: |
          sudo apt-get purge --auto-remove cmake
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
          sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get -y install gcc-10 g++-10 build-essential cmake ninja-build git file libopenimageio-dev libopencv-dev
      - name: "Configure and Build"
        run: |
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10
          cmake --build build
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Pull Submodules"
        run: |
          git submodule update --init --recursive
      - name: "Install Dependencies"
        run: |
          brew install cmake ninja openimageio opencv pybind11 spdlog llvm
      - name: "Configure and Build"
        run: |
          export PATH=$PATH:/usr/local/opt/llvm/bin
          cmake -S . -B build -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++
          cmake --build build
